; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define AppId "{{A4C5B89C-92D3-4AF9-BE3E-74B3D0C31402}}"
#define AppName "Clouva"
#define AppVersion "0.1.0"
#define AlphaVersion "1"
#define AppDisplayName "Clouva v0.1.0"
#define AppPublisher "Clouva.ai"
#define OutputDir "SetupOutput"
#define ResourcesDir "Public\assets"
#define AppIconName ""
#define DesktopIconFile ""
#define AppContact "clouvai@gmail.com"

[Setup]
SignTool=MsSign $f
AppId={#AppId}
AppName={#AppName}
AppVersion={#AppVersion}
AppPublisher={#AppPublisher}
DefaultDirName={pf}\Clouva.ai
DefaultGroupName=Clouva.ai
AllowNoIcons=yes
SetupIconFile={#AppIconName}
OutputDir={#OutputDir}
OutputBaseFilename=ClouvaSetup-v{#AppVersion}-alpha.{#AlphaVersion}
Compression=lzma
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin
ArchitecturesInstallIn64BitMode=x64compatible
UninstallDisplayIcon={app}\Clouva.exe
LicenseFile="../LICENSE"
AppCopyright=© 2026 Clouva.ai
AppContact={#AppContact}

[Languages]
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Создать ярлык на рабочем столе"; GroupDescription: "Дополнительно:"; Flags: unchecked
Name: "autostart"; Description: "Запускать вместе с Windows"; GroupDescription: "Дополнительно:"

[Files]
; Основное приложение
Source: "D:\Projects\Clouva.ai\Clouva.Desktop\bin\Release\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\Clouva"; Filename: "{app}\Clouva.exe"; IconFilename: {#DesktopIconFile}; WorkingDir: "{app}"
Name: "{userdesktop}\Clouva"; Filename: "{app}\Clouva.exe"; IconFilename: {#DesktopIconFile}; WorkingDir: "{app}"; Tasks: desktopicon

[Registry]
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "Parmigiano Desktop"; ValueData: """{app}\Parmigiano.exe"""; Tasks: autostart; Flags: uninsdeletevalue

[Run]
Filename: "{app}\Clouva.exe"; Description: "Запустить Parmigiano Chat"; Flags: nowait postinstall skipifsilent

[Code]
const
  EVENT_MODIFY_STATE = $0002;

function OpenEvent(dwDesiredAccess: Cardinal; bInheritHandle: LongBool; lpName: AnsiString): THandle; external 'OpenEventA@kernel32.dll stdcall';
function SetEvent(hEvent: THandle): LongBool; external 'SetEvent@kernel32.dll stdcall';
function CloseHandle(hObject: THandle): LongBool; external 'CloseHandle@kernel32.dll stdcall';
procedure Sleep(dwMilliseconds: Cardinal); external 'Sleep@kernel32.dll stdcall';

procedure CurUninstallStepChanged(CurStep: TUninstallStep);
begin
  if CurStep = usUninstall then
  begin
    SignalBrokerAndMaybeKill();
  end;
end;

[UninstallDelete]
Type: filesandordirs; Name: "{app}"