FROM golang:1.26-bookworm AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -o clouva.ai-linux ./cmd/server

FROM debian:bookworm-slim

WORKDIR /app

COPY --from=builder /app/clouva.ai-linux .

EXPOSE 8080

CMD ["./clouva.ai-linux"]
