FROM golang:1.26-bookworm

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

RUN go install github.com/pressly/goose/v3/cmd/goose@latest

COPY . .

RUN CGO_ENABLED=0 go build -o clouva.ai-linux ./cmd/server

EXPOSE 8080

CMD ["./clouva.ai-linux"]
