services:
    ollama_qwen:
        image: ollama/ollama
        container_name: ollama_qwen
        networks:
            - internal
        ports:
            - '11434:11434'
        environment:
            - OLLAMA_NUM_PARALLEL=4
            - OLLAMA_MAX_LOADED_MODELS=2
            - OLLAMA_KEEP_ALIVE=20m
        volumes:
            - ollama_qwen_data:/root/.ollama
        restart: unless-stopped
    ollama_phi:
        image: ollama/ollama
        container_name: ollama_phi
        networks:
            - internal
        ports:
            - '11435:11434'
        environment:
            - OLLAMA_NUM_PARALLEL=6
            - OLLAMA_MAX_LOADED_MODELS=1
            - OLLAMA_KEEP_ALIVE=30m
        volumes:
            - ollama_phi_data:/root/.ollama
        restart: unless-stopped
    db:
        image: postgres:16
        networks:
            - internal
        restart: always
        env_file:
            - ./Clouva.Server/.env.production
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 5s
            retries: 5
    redis:
        image: redis:8
        networks:
            - internal
        restart: unless-stopped
        command: redis-server --requirepass redis-clouvavp5-passw0rd
        volumes:
            - redis_data:/data

    http_server:
        networks:
            - internal
        restart: unless-stopped
        build:
            context: Clouva.Server
            dockerfile: Dockerfile.prod
        env_file: './Clouva.Server/.env.production'
        ports:
            - '8080:8080'
        depends_on:
            - ollama_qwen
            - ollama_phi
            - db
            - redis

volumes:
    postgres_data:
    redis_data:
    ollama_qwen_data:
    ollama_phi_data:

networks:
    internal:
        driver: bridge
