-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS payment_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),

    user_uuid VARCHAR(255) NOT NULL,
    plan_name TEXT NOT NULL,

    yookassa_payment_id TEXT NOT NULL,
    yookassa_payment_method_id TEXT,

    amount DECIMAL(10, 2) NOT NULL DEFAULT 0,
    currency TEXT NOT NULL DEFAULT 'RUB',

    -- pending | waiting_for_capture | succeeded | canceled | failed
    status TEXT NOT NULL DEFAULT 'pending',
    -- initial | renewal | manual
    payment_kind TEXT NOT NULL DEFAULT 'initial',

    description TEXT,
    paid_at TIMESTAMPTZ,
    metadata JSONB,

    CONSTRAINT uq_payment_history_yookassa_payment_id UNIQUE (yookassa_payment_id)
);

CREATE OR REPLACE FUNCTION set_updated_at_payment_history()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at_payment_history_trigger
    BEFORE UPDATE ON payment_history
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_payment_history();
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TRIGGER IF EXISTS set_updated_at_payment_history ON payment_history;
DROP FUNCTION IF EXISTS set_updated_at_payment_history();

DROP TABLE IF EXISTS payment_history;
-- +goose StatementEnd
