-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS user_usages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    user_uuid VARCHAR(255) NOT NULL UNIQUE,

    model_name TEXT NOT NULL,
    tokens_used INT DEFAULT 0
);

-- +Triggers
CREATE OR REPLACE FUNCTION set_updated_at_user_usages()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at_user_usages_trigger
    BEFORE UPDATE ON user_usages
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_user_usages();
-- +Triggers
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TRIGGER IF EXISTS set_updated_at_user_usages ON user_usages;
DROP FUNCTION IF EXISTS set_updated_at_user_usages();

DROP TABLE IF EXISTS user_usages;
-- +goose StatementEnd
