-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS user_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    user_uuid VARCHAR(255) NOT NULL UNIQUE,

    subscription_id INT REFERENCES subscriptions(id) ON DELETE CASCADE,
    transaction_type TEXT NOT NULL DEFAULT 'pending', -- тип: payment, pending
    amount DECIMAL(10,2) DEFAULT 0,
    currency TEXT DEFAULT 'RUB',
    description TEXT
);

-- +Triggers
CREATE OR REPLACE FUNCTION set_updated_at_user_transactions()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at_user_transactions_trigger
    BEFORE UPDATE ON user_transactions
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_user_transactions();
-- +Triggers
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TRIGGER IF EXISTS set_updated_at_user_transactions ON user_transactions;
DROP FUNCTION IF EXISTS set_updated_at_user_transactions();

DROP TABLE IF EXISTS user_transactions;
-- +goose StatementEnd
