-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),

    plan_name TEXT NOT NULL,
    amount DECIMAL(10,2) DEFAULT 0,
    currency TEXT DEFAULT 'RUB',
    duration_days INT NOT NULL DEFAULT 30,

    tokens_used INT DEFAULT 0,

    can_change_email BOOLEAN NOT NULL DEFAULT FALSE,
    can_delete_account BOOLEAN NOT NULL DEFAULT FALSE,

    description JSONB,
    features JSONB
);

INSERT INTO subscriptions (plan_name, amount, currency, duration_days, tokens_used, can_change_email, can_delete_account, description, features) VALUES (
    'Free', 0, 'RUB', 30, 55000, FALSE, FALSE,
    '{
        "en": "Perfect for everyday speech-to-text and basic productivity.",
        "ru": "Идеально для повседневного преобразования речи в текст и базовой продуктивности."
    }',
    '{
        "en": [
            "Basic monthly token limit",
            "Speech-to-text conversion",
            "Smart punctuation",
            "Filler word cleanup",
            "Standard AI response speed"
        ],
        "ru": [
            "Базовый лимит токенов в месяц",
            "Преобразование речи в текст",
            "Умная пунктуация",
            "Удаление слов-паразитов",
            "Стандартная скорость ответа AI"
        ]
    }');
INSERT INTO subscriptions (plan_name, amount, currency, duration_days, tokens_used, can_change_email, can_delete_account, description, features) VALUES (
    'Premium', 67, 'RUB', 30, 550000, TRUE, TRUE,
    '{
        "en": "Higher limits, faster AI, and advanced account controls.",
        "ru": "Больше лимитов, более быстрый AI и расширенные настройки аккаунта."
    }',
    '{
        "en": [
            "More monthly tokens",
            "Priority AI queue (faster responses)",
            "Change email address",
            "Delete account access"
        ],
        "ru": [
            "Больше токенов в месяц",
            "Приоритетная очередь AI (быстрее ответы)",
            "Изменение почты",
            "Возможность удалить аккаунт"
        ]
    }');
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS subscriptions;
-- +goose StatementEnd
