-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS user_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    user_uuid VARCHAR(255) NOT NULL UNIQUE,

    plan_name TEXT NOT NULL DEFAULT 'Free',
    valid_from TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())), -- начало действия подписки
    valid_to TIMESTAMPTZ,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

-- +Triggers
CREATE OR REPLACE FUNCTION set_updated_at_user_subscriptions()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at_user_subscriptions_trigger
    BEFORE UPDATE ON user_subscriptions
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_user_subscriptions();
-- +Triggers
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TRIGGER IF EXISTS set_updated_at_user_subscriptions ON user_subscriptions;
DROP FUNCTION IF EXISTS set_updated_at_user_subscriptions();

DROP TABLE IF EXISTS user_subscriptions;
-- +goose StatementEnd
