#!/bin/bash

set -e

# COLORS
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

BRANCH="$(git rev-parse --abbrev-ref HEAD)"

HOME="$(git rev-parse --show-toplevel)"
FILE_CONFIG="Clouva.Web/apps/.config/config.client.ts"

if [ "$BRANCH" = "preprod" ]; then
    RELEASE="preprod"
elif [ "$BRANCH" = "main" ]; then
    RELEASE="prod"
else
    RELEASE="dev"
fi

cd "$HOME/Clouva.Web"
for file in $(find . -type f \( -name "*.ts" -o -name "*.tsx" \) -not -path "*/node_modules/*"); do
    if grep -q "console.log" "$file"; then
        echo -e "${RED}Предупреждение: Найдено использование console.log в файле: $file${NC}"
    fi
done

cd "$HOME/Clouva.Web"
# Используем sed для замены release
echo -e "${BLUE}Замена release${NC}"
if sed -i "s/release: 'dev'/release: '${RELEASE}'/" "$HOME/$FILE_CONFIG"; then
    echo -e "Значение переменной release заменено $FILE_CONFIG"
else
    echo -e "Ошибка: Не удалось заменить значение в файле $FILE_CONFIG."
    exit 1
fi

cd "$HOME/Clouva.Web"
pnpm i
pnpm build
size=$(du -sm "$HOME/Clouva.Web/dist" | cut -f1)
if [ "$size" -gt 555 ]; then
    echo -e "${RED}Ошибка: Размер папки или файла больше 555 МБ: 'client/dist' (${size} MB)${NC}"
    exit 1
elif [ "$size" -gt 200 ]; then
    echo -e "${YELLOW}Предупреждение: Размер папки или файла больше 200 МБ: 'client/dist' (${size} MB)${NC}"
else
    echo -e "${GREEN}Размер папки или файла в пределах нормы: 'client/dist' (${size} MB)${NC}"
fi

echo "Скрипт успешно выполнился!"
