#!/bin/bash

set -e

echo "Stopping all docker containers..."
docker compose -f docker-compose.prod.yml down

echo "Building docker clouva.ai.server container..."
docker compose -f docker-compose.prod.yml build --no-cache

echo "Upping docker clouva.ai.server container..."
docker compose -f docker-compose.prod.yml up -d

echo "Docker done."
docker compose ps
